name: shuriken

services:
  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data: