FROM python:2.7

RUN mkdir /app
WORKDIR /app
RUN git clone https://github.com/apple/ccs-caldavtester.git
WORKDIR /app/ccs-caldavtester
RUN pip install -r requirements.txt

CMD ["python", "testcaldav.py"]