import { defineRelations } from "drizzle-orm";
import * as schema from "./schema.ts";

// ---------------------------------------------------------------------------
// Relational-query graph for drizzle's `db.query.*` API. Hand-written to mirror
// the foreign keys declared in ./schema/* — NOT generated by `drizzle-kit pull`,
// whose junction heuristic mis-models audit/index/self-reference tables
// (dav_shadow, cal_index, dav_tombstone, parent_*_id) as many-to-many joins.
//
// Conventions:
//   - The FK-owning side gets the `one` relation with `from`/`to`. `optional`
//     is false for NOT NULL columns and left at its default (true) for nullable
//     ones, so the inferred result type matches the column's nullability.
//   - The referenced side gets the reverse `many`, or `one` when a uniqueness
//     constraint makes it 1:1.
//   - Self-references and the many-to-many `through()` convenience relations
//     carry a matching `alias` on both ends so drizzle can pair them.
// ---------------------------------------------------------------------------

export const relations = defineRelations(schema, (r) => ({
	principal: {
		// 1:1 — `user`/`group` each own a unique `principal_id`.
		user: r.one.user(),
		group: r.one.group(),
		ownedCollections: r.many.davCollection(),
		acls: r.many.davAcl(),
	},
	user: {
		principal: r.one.principal({
			from: r.user.principalId,
			to: r.principal.id,
			optional: false,
		}),
		authUsers: r.many.authUser(),
		memberships: r.many.membership(),
		emailCredential: r.one.userEmailCredential(),
		shareLinks: r.many.shareLink(),
		// M:N convenience over the `membership` junction.
		groups: r.many.group({
			from: r.user.id.through(r.membership.userId),
			to: r.group.id.through(r.membership.groupId),
			alias: "user_groups",
		}),
	},
	authUser: {
		user: r.one.user({
			from: r.authUser.userId,
			to: r.user.id,
			optional: false,
		}),
	},
	group: {
		principal: r.one.principal({
			from: r.group.principalId,
			to: r.principal.id,
			optional: false,
		}),
		memberships: r.many.membership(),
		members: r.many.user({
			from: r.group.id.through(r.membership.groupId),
			to: r.user.id.through(r.membership.userId),
			alias: "user_groups",
		}),
	},
	membership: {
		user: r.one.user({
			from: r.membership.userId,
			to: r.user.id,
			optional: false,
		}),
		group: r.one.group({
			from: r.membership.groupId,
			to: r.group.id,
			optional: false,
		}),
	},
	davAcl: {
		// principal_id is nullable (pseudo-principals like 'all'/'authenticated').
		principal: r.one.principal({
			from: r.davAcl.principalId,
			to: r.principal.id,
		}),
	},
	davEntity: {
		components: r.many.davComponent(),
		instances: r.many.davInstance(),
		scheduleMessages: r.many.davScheduleMessage(),
		shadows: r.many.davShadow(),
		tombstones: r.many.davTombstone(),
		calIndexEntries: r.many.calIndex(),
		// 1:1 — card_index PK is entity_id.
		cardIndex: r.one.cardIndex(),
	},
	davCollection: {
		owner: r.one.principal({
			from: r.davCollection.ownerPrincipalId,
			to: r.principal.id,
			optional: false,
		}),
		// Self-reference: collection hierarchy.
		parent: r.one.davCollection({
			from: r.davCollection.parentCollectionId,
			to: r.davCollection.id,
			alias: "collection_parent",
		}),
		children: r.many.davCollection({ alias: "collection_parent" }),
		// Self-reference: inbox's default target calendar (RFC 6638).
		scheduleDefaultCalendar: r.one.davCollection({
			from: r.davCollection.scheduleDefaultCalendarId,
			to: r.davCollection.id,
			alias: "collection_schedule_default",
		}),
		defaultForCollections: r.many.davCollection({
			alias: "collection_schedule_default",
		}),
		instances: r.many.davInstance(),
		scheduleMessages: r.many.davScheduleMessage(),
		tombstones: r.many.davTombstone(),
		// 1:1 — claim has a unique collection_id.
		externalCalendarClaim: r.one.externalCalendarClaim(),
		shareLinkCalendars: r.many.shareLinkCalendars(),
		shareLinks: r.many.shareLink({
			from: r.davCollection.id.through(r.shareLinkCalendars.calendarId),
			to: r.shareLink.id.through(r.shareLinkCalendars.shareLinkId),
			alias: "sharelink_calendars",
		}),
	},
	davComponent: {
		entity: r.one.davEntity({
			from: r.davComponent.entityId,
			to: r.davEntity.id,
			optional: false,
		}),
		// Self-reference: component nesting (e.g. VALARM within VEVENT).
		parent: r.one.davComponent({
			from: r.davComponent.parentComponentId,
			to: r.davComponent.id,
			alias: "component_parent",
		}),
		children: r.many.davComponent({ alias: "component_parent" }),
		properties: r.many.davProperty(),
		calIndexEntries: r.many.calIndex(),
	},
	davProperty: {
		component: r.one.davComponent({
			from: r.davProperty.componentId,
			to: r.davComponent.id,
			optional: false,
		}),
		parameters: r.many.davParameter(),
	},
	davParameter: {
		property: r.one.davProperty({
			from: r.davParameter.propertyId,
			to: r.davProperty.id,
			optional: false,
		}),
	},
	davInstance: {
		collection: r.one.davCollection({
			from: r.davInstance.collectionId,
			to: r.davCollection.id,
			optional: false,
		}),
		entity: r.one.davEntity({
			from: r.davInstance.entityId,
			to: r.davEntity.id,
			optional: false,
		}),
		shadows: r.many.davShadow(),
	},
	davScheduleMessage: {
		collection: r.one.davCollection({
			from: r.davScheduleMessage.collectionId,
			to: r.davCollection.id,
			optional: false,
		}),
		entity: r.one.davEntity({
			from: r.davScheduleMessage.entityId,
			to: r.davEntity.id,
			optional: false,
		}),
	},
	davShadow: {
		// Both refs are nullable (a CHECK requires at least one to be set).
		instance: r.one.davInstance({
			from: r.davShadow.instanceId,
			to: r.davInstance.id,
		}),
		entity: r.one.davEntity({
			from: r.davShadow.entityId,
			to: r.davEntity.id,
		}),
	},
	davTombstone: {
		collection: r.one.davCollection({
			from: r.davTombstone.collectionId,
			to: r.davCollection.id,
			optional: false,
		}),
		// entity_id is nullable (ON DELETE SET NULL).
		entity: r.one.davEntity({
			from: r.davTombstone.entityId,
			to: r.davEntity.id,
		}),
	},
	calIndex: {
		entity: r.one.davEntity({
			from: r.calIndex.entityId,
			to: r.davEntity.id,
			optional: false,
		}),
		component: r.one.davComponent({
			from: r.calIndex.componentId,
			to: r.davComponent.id,
			optional: false,
		}),
	},
	cardIndex: {
		entity: r.one.davEntity({
			from: r.cardIndex.entityId,
			to: r.davEntity.id,
			optional: false,
		}),
	},
	externalCalendar: {
		claims: r.many.externalCalendarClaim(),
	},
	externalCalendarClaim: {
		externalCalendar: r.one.externalCalendar({
			from: r.externalCalendarClaim.externalCalendarId,
			to: r.externalCalendar.id,
			optional: false,
		}),
		collection: r.one.davCollection({
			from: r.externalCalendarClaim.collectionId,
			to: r.davCollection.id,
			optional: false,
		}),
	},
	userEmailCredential: {
		user: r.one.user({
			from: r.userEmailCredential.userId,
			to: r.user.id,
			optional: false,
		}),
	},
	shareLink: {
		user: r.one.user({
			from: r.shareLink.userId,
			to: r.user.id,
			optional: false,
		}),
		shareLinkCalendars: r.many.shareLinkCalendars(),
		calendars: r.many.davCollection({
			from: r.shareLink.id.through(r.shareLinkCalendars.shareLinkId),
			to: r.davCollection.id.through(r.shareLinkCalendars.calendarId),
			alias: "sharelink_calendars",
		}),
	},
	shareLinkCalendars: {
		shareLink: r.one.shareLink({
			from: r.shareLinkCalendars.shareLinkId,
			to: r.shareLink.id,
			optional: false,
		}),
		calendar: r.one.davCollection({
			from: r.shareLinkCalendars.calendarId,
			to: r.davCollection.id,
			optional: false,
		}),
	},
}));
