// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// Generated from the docs/ folder structure: docs/intro.md, then the
	// admin/ and user/ categories (ordered via each _category_.json and each
	// page's sidebar_position frontmatter).
	docsSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
