// @generated automatically by Diesel CLI.

diesel::table! {
    /// External authentication provider mappings for users (OAuth, LDAP, etc.)
    auth_users (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Reference to the user account
        user_id -> Uuid,
        /// Authentication provider identifier (e.g., "google", "github", "ldap")
        auth_source -> Text,
        /// User identifier from the authentication provider
        auth_id -> Text,
        /// The `created_at` column of the `auth_users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `auth_users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Organizational groups for collaborative sharing of calendars and contacts
    groups (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// The `created_at` column of the `groups` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `groups` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// User accounts for the CalDAV/CardDAV server
    users (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Display name of the user
        name -> Text,
        /// Unique email address for the user
        email -> Text,
        /// Optional group membership for shared calendar/contact access
        group_id -> Nullable<Uuid>,
        /// The `created_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::joinable!(auth_users -> users (user_id));
diesel::joinable!(users -> groups (group_id));

diesel::allow_tables_to_appear_in_same_query!(auth_users, groups, users,);
