// @generated automatically by Diesel CLI.

diesel::table! {
    /// External authentication provider mappings for users (OAuth, LDAP, etc.)
    auth_users (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Reference to the user account
        user_id -> Uuid,
        /// Authentication provider identifier (e.g., "google", "github", "ldap")
        auth_source -> Text,
        /// User identifier from the authentication provider
        auth_id -> Text,
        /// The `updated_at` column of the `auth_users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Casbin authorization rules table
    casbin_rule (id) {
        /// The `id` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `ptype` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        ptype -> Varchar,
        /// The `v0` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        v0 -> Varchar,
        /// The `v1` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        v1 -> Varchar,
        /// The `v2` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        v2 -> Varchar,
        /// The `v3` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        v3 -> Varchar,
        /// The `v4` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        v4 -> Varchar,
        /// The `v5` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        v5 -> Varchar,
    }
}

diesel::table! {
    /// Organizational groups for collaborative sharing of calendars and contacts
    groups (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// The `updated_at` column of the `groups` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// User accounts for the CalDAV/CardDAV server
    users (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Display name of the user
        name -> Text,
        /// Unique email address for the user
        email -> Text,
        /// Optional group membership for shared calendar/contact access
        group_id -> Nullable<Uuid>,
        /// The `updated_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::joinable!(auth_users -> users (user_id));
diesel::joinable!(users -> groups (group_id));

diesel::allow_tables_to_appear_in_same_query!(auth_users, casbin_rule, groups, users,);
