// @generated automatically by Diesel CLI.
#![allow(clippy::wildcard_imports)]

/// A module containing custom SQL type definitions
///
/// (Automatically generated by Diesel.)
pub mod sql_types {
    /// The `pg_catalog.tsvector` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::query_builder::QueryId, Clone, diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "tsvector", schema = "pg_catalog"))]
    pub struct Tsvector;
}

diesel::table! {
    /// External authentication provider mappings for users (`OAuth`, LDAP, etc.)
    auth_user (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Reference to the user account
        user_id -> Uuid,
        /// Authentication provider identifier (e.g., "google", "github", "ldap")
        auth_source -> Text,
        /// User identifier from the authentication provider
        auth_id -> Text,
        /// The `updated_at` column of the `auth_user` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Derived index for CalDAV queries (time-range, UID lookups, etc.)
    cal_index (entity_id, component_id) {
        /// Canonical entity
        entity_id -> Uuid,
        /// Component indexed (e.g., VEVENT component)
        component_id -> Uuid,
        /// The `component_type` column of the `cal_index` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        component_type -> Text,
        /// The `uid` column of the `cal_index` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Nullable<Text>,
        /// The `recurrence_id_utc` column of the `cal_index` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        recurrence_id_utc -> Nullable<Timestamptz>,
        /// The `dtstart_utc` column of the `cal_index` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        dtstart_utc -> Nullable<Timestamptz>,
        /// The `dtend_utc` column of the `cal_index` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        dtend_utc -> Nullable<Timestamptz>,
        /// The `all_day` column of the `cal_index` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        all_day -> Nullable<Bool>,
        /// The `rrule_text` column of the `cal_index` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        rrule_text -> Nullable<Text>,
        /// The `organizer` column of the `cal_index` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        organizer -> Nullable<Text>,
        /// The `summary` column of the `cal_index` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        summary -> Nullable<Text>,
        /// The `location` column of the `cal_index` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        location -> Nullable<Text>,
        /// The `sequence` column of the `cal_index` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        sequence -> Nullable<Int4>,
        /// The `updated_at` column of the `cal_index` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `deleted_at` column of the `cal_index` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Derived occurrence expansion cache for recurring components (optional)
    cal_occurrence (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// The `entity_id` column of the `cal_occurrence` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        entity_id -> Uuid,
        /// The `component_id` column of the `cal_occurrence` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        component_id -> Uuid,
        /// Occurrence start time (UTC)
        start_utc -> Timestamptz,
        /// Occurrence end time (UTC)
        end_utc -> Timestamptz,
        /// The `recurrence_id_utc` column of the `cal_occurrence` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        recurrence_id_utc -> Nullable<Timestamptz>,
        /// The `updated_at` column of the `cal_occurrence` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `deleted_at` column of the `cal_occurrence` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Derived index of vCard email addresses
    card_email (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// The `entity_id` column of the `card_email` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        entity_id -> Uuid,
        /// The `email` column of the `card_email` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Text,
        /// The `params_json` column of the `card_email` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        params_json -> Nullable<Jsonb>,
        /// The `ordinal` column of the `card_email` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        ordinal -> Int4,
        /// The `updated_at` column of the `card_email` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `deleted_at` column of the `card_email` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::Tsvector;

    /// Derived index for CardDAV queries (FN, UID, text search)
    card_index (entity_id) {
        /// Canonical entity
        entity_id -> Uuid,
        /// The `uid` column of the `card_index` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        uid -> Nullable<Text>,
        /// The `fn` column of the `card_index` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        #[sql_name = "fn"]
        fn_ -> Nullable<Text>,
        /// The `n_family` column of the `card_index` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        n_family -> Nullable<Text>,
        /// The `n_given` column of the `card_index` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        n_given -> Nullable<Text>,
        /// The `org` column of the `card_index` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        org -> Nullable<Text>,
        /// The `title` column of the `card_index` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Nullable<Text>,
        /// The `search_tsv` column of the `card_index` table.
        ///
        /// Its SQL type is `Nullable<Tsvector>`.
        ///
        /// (Automatically generated by Diesel.)
        search_tsv -> Nullable<Tsvector>,
        /// The `updated_at` column of the `card_index` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `deleted_at` column of the `card_index` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Derived index of vCard phone numbers
    card_phone (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// The `entity_id` column of the `card_phone` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        entity_id -> Uuid,
        /// The `phone_raw` column of the `card_phone` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        phone_raw -> Text,
        /// The `phone_norm` column of the `card_phone` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        phone_norm -> Nullable<Text>,
        /// The `params_json` column of the `card_phone` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        params_json -> Nullable<Jsonb>,
        /// The `ordinal` column of the `card_phone` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        ordinal -> Int4,
        /// The `updated_at` column of the `card_phone` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `deleted_at` column of the `card_phone` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Casbin authorization rules table
    casbin_rule (id) {
        /// The `id` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `ptype` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        ptype -> Varchar,
        /// The `v0` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        v0 -> Varchar,
        /// The `v1` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        v1 -> Varchar,
        /// The `v2` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        v2 -> Varchar,
        /// The `v3` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        v3 -> Varchar,
        /// The `v4` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        v4 -> Varchar,
        /// The `v5` column of the `casbin_rule` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        v5 -> Varchar,
    }
}

diesel::table! {
    /// DAV collections (CalDAV calendars, CardDAV addressbooks)
    dav_collection (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Owner principal of this collection
        owner_principal_id -> Uuid,
        /// calendar or addressbook
        collection_type -> Text,
        /// Collection URI (unique per owner)
        uri -> Text,
        /// The `display_name` column of the `dav_collection` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        display_name -> Nullable<Text>,
        /// The `description` column of the `dav_collection` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `timezone_tzid` column of the `dav_collection` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        timezone_tzid -> Nullable<Text>,
        /// Monotonic collection sync token
        synctoken -> Int8,
        /// The `updated_at` column of the `dav_collection` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// Soft-delete timestamp (undo window / pending purge)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Canonical component tree for iCalendar/vCard content
    dav_component (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Owning canonical entity
        entity_id -> Uuid,
        /// Parent component for nested structures (e.g., VCALENDAR -> VEVENT -> VALARM)
        parent_component_id -> Nullable<Uuid>,
        /// Component name (e.g., VEVENT, VCARD)
        name -> Text,
        /// Ordering within the parent scope
        ordinal -> Int4,
        /// The `updated_at` column of the `dav_component` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// Soft-delete timestamp (rare; usually delete entire entity)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Canonical content entity (shared across one or more DAV instances)
    dav_entity (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// icalendar or vcard
        entity_type -> Text,
        /// Logical UID inside the content (not globally unique)
        logical_uid -> Nullable<Text>,
        /// The `updated_at` column of the `dav_entity` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// Soft-delete timestamp (undo window / pending purge)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Per-collection resource identity that references a canonical `dav_entity`
    dav_instance (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Containing collection
        collection_id -> Uuid,
        /// Referenced canonical entity
        entity_id -> Uuid,
        /// Resource URI within collection
        uri -> Text,
        /// text/calendar or text/vcard
        content_type -> Text,
        /// ETag for this resource
        etag -> Text,
        /// Monotonic per-collection change revision for sync
        sync_revision -> Int8,
        /// The `last_modified` column of the `dav_instance` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        last_modified -> Timestamptz,
        /// The `updated_at` column of the `dav_instance` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// Soft-delete timestamp (undo window / pending purge)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Parameters associated with a property (including ordering for stable canonical output)
    dav_parameter (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Owning property
        property_id -> Uuid,
        /// Parameter name (e.g., TZID, TYPE)
        name -> Text,
        /// Parameter value
        value -> Text,
        /// Ordering within the parameter list
        ordinal -> Int4,
        /// The `updated_at` column of the `dav_parameter` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `deleted_at` column of the `dav_parameter` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Canonical properties for a component, including X-* extensions; value stored in exactly one typed column
    dav_property (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Owning component
        component_id -> Uuid,
        /// Property name (e.g., DTSTART, FN, TEL)
        name -> Text,
        /// Canonical value type for deterministic serialization
        value_type -> Text,
        /// The `value_text` column of the `dav_property` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        value_text -> Nullable<Text>,
        /// The `value_int` column of the `dav_property` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        value_int -> Nullable<Int8>,
        /// The `value_float` column of the `dav_property` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        value_float -> Nullable<Float8>,
        /// The `value_bool` column of the `dav_property` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        value_bool -> Nullable<Bool>,
        /// The `value_date` column of the `dav_property` table.
        ///
        /// Its SQL type is `Nullable<Date>`.
        ///
        /// (Automatically generated by Diesel.)
        value_date -> Nullable<Date>,
        /// The `value_tstz` column of the `dav_property` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        value_tstz -> Nullable<Timestamptz>,
        /// The `value_bytes` column of the `dav_property` table.
        ///
        /// Its SQL type is `Nullable<Bytea>`.
        ///
        /// (Automatically generated by Diesel.)
        value_bytes -> Nullable<Bytea>,
        /// The `value_json` column of the `dav_property` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        value_json -> Nullable<Jsonb>,
        /// Ordering within component
        ordinal -> Int4,
        /// The `updated_at` column of the `dav_property` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// Soft-delete timestamp (rare; usually delete entity)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Debug shadow storage of original inbound payload and canonical serialized payload
    dav_shadow (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Related DAV instance (if known)
        instance_id -> Nullable<Uuid>,
        /// Related canonical entity (if known)
        entity_id -> Nullable<Uuid>,
        /// inbound or outbound
        direction -> Text,
        /// The `content_type` column of the `dav_shadow` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        content_type -> Text,
        /// Client-sent payload bytes
        raw_original -> Nullable<Bytea>,
        /// Canonical serialized payload bytes
        raw_canonical -> Nullable<Bytea>,
        /// Optional parse/validation diagnostics
        diagnostics -> Nullable<Jsonb>,
        /// The `request_id` column of the `dav_shadow` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        request_id -> Nullable<Text>,
        /// The `updated_at` column of the `dav_shadow` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// Soft-delete timestamp for shadow retention
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Deletion tombstones for sync correctness after purge
    dav_tombstone (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Collection where the resource was deleted
        collection_id -> Uuid,
        /// Resource URI that was deleted
        uri -> Text,
        /// The `entity_id` column of the `dav_tombstone` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        entity_id -> Nullable<Uuid>,
        /// Collection synctoken at deletion time
        synctoken -> Int8,
        /// Per-collection revision at deletion time
        sync_revision -> Int8,
        /// Deletion time
        deleted_at -> Timestamptz,
        /// The `last_etag` column of the `dav_tombstone` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        last_etag -> Nullable<Text>,
        /// The `logical_uid` column of the `dav_tombstone` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        logical_uid -> Nullable<Text>,
    }
}

diesel::table! {
    /// Organizational groups for collaborative sharing of calendars and contacts
    group (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// The `updated_at` column of the `group` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// Primary name identifier for the group
        primary_name -> Nullable<Uuid>,
        /// Reference to principal row representing this group
        principal_id -> Uuid,
    }
}

diesel::table! {
    /// Group names and aliases
    group_name (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Reference to the group
        group_id -> Uuid,
        /// Unique name for the group
        name -> Text,
        /// The `updated_at` column of the `group_name` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Many-to-many relationship between users and groups
    membership (user_id, group_id) {
        /// Reference to the user
        user_id -> Uuid,
        /// Reference to the group
        group_id -> Uuid,
        /// The `updated_at` column of the `membership` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Unified principal namespace for ACL subjects (users, groups, system/public/resource principals)
    principal (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Principal category
        principal_type -> Text,
        /// Stable principal URI used by DAV routing/discovery
        uri -> Text,
        /// Human-readable display name
        display_name -> Nullable<Text>,
        /// The `updated_at` column of the `principal` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// Soft-delete timestamp (principal disabled / pending purge)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// User accounts for the CalDAV/CardDAV server
    user (id) {
        /// UUID v7 primary key
        id -> Uuid,
        /// Display name of the user
        name -> Text,
        /// Unique email address for the user
        email -> Text,
        /// The `updated_at` column of the `user` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// Reference to principal row representing this user
        principal_id -> Uuid,
    }
}

diesel::joinable!(auth_user -> user (user_id));
diesel::joinable!(cal_index -> dav_component (component_id));
diesel::joinable!(cal_index -> dav_entity (entity_id));
diesel::joinable!(cal_occurrence -> dav_component (component_id));
diesel::joinable!(cal_occurrence -> dav_entity (entity_id));
diesel::joinable!(card_email -> dav_entity (entity_id));
diesel::joinable!(card_index -> dav_entity (entity_id));
diesel::joinable!(card_phone -> dav_entity (entity_id));
diesel::joinable!(dav_collection -> principal (owner_principal_id));
diesel::joinable!(dav_component -> dav_entity (entity_id));
diesel::joinable!(dav_instance -> dav_collection (collection_id));
diesel::joinable!(dav_instance -> dav_entity (entity_id));
diesel::joinable!(dav_parameter -> dav_property (property_id));
diesel::joinable!(dav_property -> dav_component (component_id));
diesel::joinable!(dav_shadow -> dav_entity (entity_id));
diesel::joinable!(dav_shadow -> dav_instance (instance_id));
diesel::joinable!(dav_tombstone -> dav_collection (collection_id));
diesel::joinable!(dav_tombstone -> dav_entity (entity_id));
diesel::joinable!(group -> principal (principal_id));
diesel::joinable!(membership -> group (group_id));
diesel::joinable!(membership -> user (user_id));
diesel::joinable!(user -> principal (principal_id));

diesel::allow_tables_to_appear_in_same_query!(
    auth_user,
    cal_index,
    cal_occurrence,
    card_email,
    card_index,
    card_phone,
    casbin_rule,
    dav_collection,
    dav_component,
    dav_entity,
    dav_instance,
    dav_parameter,
    dav_property,
    dav_shadow,
    dav_tombstone,
    group,
    group_name,
    membership,
    principal,
    user,
);
