{{- if not .Values.existingSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shuriken.secretName" . }}
  labels: {{- include "shuriken.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.config.database.url }}
  DATABASE_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.auth.adminPassword }}
  ADMIN_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.auth.oidcClientSecret }}
  OIDC_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.mail.defaultPassword }}
  SMTP_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.mail.credsKey }}
  EMAIL_CREDS_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.mail.profilesJson }}
  SMTP_PROFILES_JSON: {{ . | quote }}
  {{- end }}
{{- end }}
