apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shuriken.secretName" . }}
  labels: {{- include "shuriken.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if and .Values.config.database.url (not .Values.config.database.existingSecret.name) }}
  DATABASE_URL: {{ .Values.config.database.url | quote }}
  {{- end }}
  {{- if and .Values.config.auth.adminPassword (not .Values.config.auth.adminPasswordExistingSecret.name) }}
  ADMIN_PASSWORD: {{ .Values.config.auth.adminPassword | quote }}
  {{- end }}
  {{- if and .Values.config.auth.oidcClientSecret (not .Values.config.auth.oidcClientSecretExistingSecret.name) }}
  OIDC_CLIENT_SECRET: {{ .Values.config.auth.oidcClientSecret | quote }}
  {{- end }}
  {{- if and .Values.config.mail.defaultPassword (not .Values.config.mail.defaultPasswordExistingSecret.name) }}
  SMTP_PASSWORD: {{ .Values.config.mail.defaultPassword | quote }}
  {{- end }}
  {{- if and .Values.config.mail.credsKey (not .Values.config.mail.credsKeyExistingSecret.name) }}
  EMAIL_CREDS_KEY: {{ .Values.config.mail.credsKey | quote }}
  {{- end }}
  {{- if and .Values.config.mail.profilesJson (not .Values.config.mail.profilesJsonExistingSecret.name) }}
  SMTP_PROFILES_JSON: {{ .Values.config.mail.profilesJson | quote }}
  {{- end }}
