apiVersion: v1
kind: Service
metadata:
  name: {{ include "shuriken.fullname" . }}
  labels:
    {{- include "shuriken.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (merge (dict) .Values.service.annotations .Values.commonAnnotations) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "shuriken.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if .Values.config.metrics.enabled }}
    - name: metrics
      port: {{ .Values.config.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    {{- if and .Values.config.mail.lmtpEnabled .Values.service.lmtp.enabled }}
    - name: lmtp
      port: {{ .Values.service.lmtp.port }}
      targetPort: lmtp
      protocol: TCP
    {{- end }}
