-- ---------------------------------------------------------------------------
-- share_link.token + share_link.display_name — completes the previously
-- stubbed share_link tables so they can power public /feed/<token>.ics URLs.
--
-- Token is URL-safe random (32 hex chars). Backfill uses md5(random()) which
-- is portable across Postgres and PGlite (no pgcrypto dependency). Tokens
-- generated by the application use crypto.getRandomValues() — the backfill
-- only matters if anyone manually seeded a row before this migration ran.
-- ---------------------------------------------------------------------------

ALTER TABLE "share_link" ADD COLUMN "token" text;
--> statement-breakpoint

ALTER TABLE "share_link" ADD COLUMN "display_name" text;
--> statement-breakpoint

UPDATE "share_link"
SET token = md5(random()::text || clock_timestamp()::text)
WHERE token IS NULL;
--> statement-breakpoint

ALTER TABLE "share_link" ALTER COLUMN "token" SET NOT NULL;
--> statement-breakpoint

ALTER TABLE "share_link" ADD CONSTRAINT "share_link_token_unique" UNIQUE ("token");
